package com.fh.entity.system;

import java.io.Serializable;
import java.util.Date;

public class SysRequestLog implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_request_log.LOG_ID
     *
     * @mbggenerated Tue Mar 14 11:46:38 CST 2017
     */
    private Long logId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_request_log.BEGIN_TIME
     *
     * @mbggenerated Tue Mar 14 11:46:38 CST 2017
     */
    private Date beginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_request_log.END_TIME
     *
     * @mbggenerated Tue Mar 14 11:46:38 CST 2017
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_request_log.REQUEST_TIME
     *
     * @mbggenerated Tue Mar 14 11:46:38 CST 2017
     */
    private Integer requestTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_request_log.LOGIN_NAME
     *
     * @mbggenerated Tue Mar 14 11:46:38 CST 2017
     */
    private String loginName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_request_log.SESSION_ID
     *
     * @mbggenerated Tue Mar 14 11:46:38 CST 2017
     */
    private String sessionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_request_log.SCHEME
     *
     * @mbggenerated Tue Mar 14 11:46:38 CST 2017
     */
    private String scheme;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_request_log.SERVER_NAME
     *
     * @mbggenerated Tue Mar 14 11:46:38 CST 2017
     */
    private String serverName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_request_log.SERVER_PORT
     *
     * @mbggenerated Tue Mar 14 11:46:38 CST 2017
     */
    private Integer serverPort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_request_log.REQUEST_URI
     *
     * @mbggenerated Tue Mar 14 11:46:38 CST 2017
     */
    private String requestUri;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_request_log.METHOD
     *
     * @mbggenerated Tue Mar 14 11:46:38 CST 2017
     */
    private String method;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_request_log.REQUEST_PARAMS
     *
     * @mbggenerated Tue Mar 14 11:46:38 CST 2017
     */
    private String requestParams;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_request_log.MOBILE_PAT
     *
     * @mbggenerated Tue Mar 14 11:46:38 CST 2017
     */
    private Integer mobilePat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_request_log.CHARACTER_ENCODING
     *
     * @mbggenerated Tue Mar 14 11:46:38 CST 2017
     */
    private String characterEncoding;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_request_log.CONTENT_LENGTH
     *
     * @mbggenerated Tue Mar 14 11:46:38 CST 2017
     */
    private Integer contentLength;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_request_log.LOCAL_ADDR
     *
     * @mbggenerated Tue Mar 14 11:46:38 CST 2017
     */
    private String localAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_request_log.LOCAL_NAME
     *
     * @mbggenerated Tue Mar 14 11:46:38 CST 2017
     */
    private String localName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_request_log.LOCAL_PORT
     *
     * @mbggenerated Tue Mar 14 11:46:38 CST 2017
     */
    private Integer localPort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_request_log.JVM_MAX_MEMORY
     *
     * @mbggenerated Tue Mar 14 11:46:38 CST 2017
     */
    private Integer jvmMaxMemory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_request_log.JVM_TOTAL_MEMORY
     *
     * @mbggenerated Tue Mar 14 11:46:38 CST 2017
     */
    private Integer jvmTotalMemory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_request_log.JVM_FREE_MEMORY
     *
     * @mbggenerated Tue Mar 14 11:46:38 CST 2017
     */
    private Integer jvmFreeMemory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_request_log.JVM_USER_MEMORY
     *
     * @mbggenerated Tue Mar 14 11:46:38 CST 2017
     */
    private Integer jvmUserMemory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_request_log.CREATE_DATE
     *
     * @mbggenerated Tue Mar 14 11:46:38 CST 2017
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_request_log
     *
     * @mbggenerated Tue Mar 14 11:46:38 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_request_log.LOG_ID
     *
     * @return the value of sys_request_log.LOG_ID
     *
     * @mbggenerated Tue Mar 14 11:46:38 CST 2017
     */
    public Long getLogId() {
        return logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_request_log.LOG_ID
     *
     * @param logId the value for sys_request_log.LOG_ID
     *
     * @mbggenerated Tue Mar 14 11:46:38 CST 2017
     */
    public void setLogId(Long logId) {
        this.logId = logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_request_log.BEGIN_TIME
     *
     * @return the value of sys_request_log.BEGIN_TIME
     *
     * @mbggenerated Tue Mar 14 11:46:38 CST 2017
     */
    public Date getBeginTime() {
        return beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_request_log.BEGIN_TIME
     *
     * @param beginTime the value for sys_request_log.BEGIN_TIME
     *
     * @mbggenerated Tue Mar 14 11:46:38 CST 2017
     */
    public void setBeginTime(Date beginTime) {
        this.beginTime = beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_request_log.END_TIME
     *
     * @return the value of sys_request_log.END_TIME
     *
     * @mbggenerated Tue Mar 14 11:46:38 CST 2017
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_request_log.END_TIME
     *
     * @param endTime the value for sys_request_log.END_TIME
     *
     * @mbggenerated Tue Mar 14 11:46:38 CST 2017
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_request_log.REQUEST_TIME
     *
     * @return the value of sys_request_log.REQUEST_TIME
     *
     * @mbggenerated Tue Mar 14 11:46:38 CST 2017
     */
    public Integer getRequestTime() {
        return requestTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_request_log.REQUEST_TIME
     *
     * @param requestTime the value for sys_request_log.REQUEST_TIME
     *
     * @mbggenerated Tue Mar 14 11:46:38 CST 2017
     */
    public void setRequestTime(Integer requestTime) {
        this.requestTime = requestTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_request_log.LOGIN_NAME
     *
     * @return the value of sys_request_log.LOGIN_NAME
     *
     * @mbggenerated Tue Mar 14 11:46:38 CST 2017
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_request_log.LOGIN_NAME
     *
     * @param loginName the value for sys_request_log.LOGIN_NAME
     *
     * @mbggenerated Tue Mar 14 11:46:38 CST 2017
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_request_log.SESSION_ID
     *
     * @return the value of sys_request_log.SESSION_ID
     *
     * @mbggenerated Tue Mar 14 11:46:38 CST 2017
     */
    public String getSessionId() {
        return sessionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_request_log.SESSION_ID
     *
     * @param sessionId the value for sys_request_log.SESSION_ID
     *
     * @mbggenerated Tue Mar 14 11:46:38 CST 2017
     */
    public void setSessionId(String sessionId) {
        this.sessionId = sessionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_request_log.SCHEME
     *
     * @return the value of sys_request_log.SCHEME
     *
     * @mbggenerated Tue Mar 14 11:46:38 CST 2017
     */
    public String getScheme() {
        return scheme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_request_log.SCHEME
     *
     * @param scheme the value for sys_request_log.SCHEME
     *
     * @mbggenerated Tue Mar 14 11:46:38 CST 2017
     */
    public void setScheme(String scheme) {
        this.scheme = scheme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_request_log.SERVER_NAME
     *
     * @return the value of sys_request_log.SERVER_NAME
     *
     * @mbggenerated Tue Mar 14 11:46:38 CST 2017
     */
    public String getServerName() {
        return serverName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_request_log.SERVER_NAME
     *
     * @param serverName the value for sys_request_log.SERVER_NAME
     *
     * @mbggenerated Tue Mar 14 11:46:38 CST 2017
     */
    public void setServerName(String serverName) {
        this.serverName = serverName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_request_log.SERVER_PORT
     *
     * @return the value of sys_request_log.SERVER_PORT
     *
     * @mbggenerated Tue Mar 14 11:46:38 CST 2017
     */
    public Integer getServerPort() {
        return serverPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_request_log.SERVER_PORT
     *
     * @param serverPort the value for sys_request_log.SERVER_PORT
     *
     * @mbggenerated Tue Mar 14 11:46:38 CST 2017
     */
    public void setServerPort(Integer serverPort) {
        this.serverPort = serverPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_request_log.REQUEST_URI
     *
     * @return the value of sys_request_log.REQUEST_URI
     *
     * @mbggenerated Tue Mar 14 11:46:38 CST 2017
     */
    public String getRequestUri() {
        return requestUri;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_request_log.REQUEST_URI
     *
     * @param requestUri the value for sys_request_log.REQUEST_URI
     *
     * @mbggenerated Tue Mar 14 11:46:38 CST 2017
     */
    public void setRequestUri(String requestUri) {
        this.requestUri = requestUri;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_request_log.METHOD
     *
     * @return the value of sys_request_log.METHOD
     *
     * @mbggenerated Tue Mar 14 11:46:38 CST 2017
     */
    public String getMethod() {
        return method;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_request_log.METHOD
     *
     * @param method the value for sys_request_log.METHOD
     *
     * @mbggenerated Tue Mar 14 11:46:38 CST 2017
     */
    public void setMethod(String method) {
        this.method = method;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_request_log.REQUEST_PARAMS
     *
     * @return the value of sys_request_log.REQUEST_PARAMS
     *
     * @mbggenerated Tue Mar 14 11:46:38 CST 2017
     */
    public String getRequestParams() {
        return requestParams;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_request_log.REQUEST_PARAMS
     *
     * @param requestParams the value for sys_request_log.REQUEST_PARAMS
     *
     * @mbggenerated Tue Mar 14 11:46:38 CST 2017
     */
    public void setRequestParams(String requestParams) {
        this.requestParams = requestParams;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_request_log.MOBILE_PAT
     *
     * @return the value of sys_request_log.MOBILE_PAT
     *
     * @mbggenerated Tue Mar 14 11:46:38 CST 2017
     */
    public Integer getMobilePat() {
        return mobilePat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_request_log.MOBILE_PAT
     *
     * @param mobilePat the value for sys_request_log.MOBILE_PAT
     *
     * @mbggenerated Tue Mar 14 11:46:38 CST 2017
     */
    public void setMobilePat(Integer mobilePat) {
        this.mobilePat = mobilePat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_request_log.CHARACTER_ENCODING
     *
     * @return the value of sys_request_log.CHARACTER_ENCODING
     *
     * @mbggenerated Tue Mar 14 11:46:38 CST 2017
     */
    public String getCharacterEncoding() {
        return characterEncoding;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_request_log.CHARACTER_ENCODING
     *
     * @param characterEncoding the value for sys_request_log.CHARACTER_ENCODING
     *
     * @mbggenerated Tue Mar 14 11:46:38 CST 2017
     */
    public void setCharacterEncoding(String characterEncoding) {
        this.characterEncoding = characterEncoding;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_request_log.CONTENT_LENGTH
     *
     * @return the value of sys_request_log.CONTENT_LENGTH
     *
     * @mbggenerated Tue Mar 14 11:46:38 CST 2017
     */
    public Integer getContentLength() {
        return contentLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_request_log.CONTENT_LENGTH
     *
     * @param contentLength the value for sys_request_log.CONTENT_LENGTH
     *
     * @mbggenerated Tue Mar 14 11:46:38 CST 2017
     */
    public void setContentLength(Integer contentLength) {
        this.contentLength = contentLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_request_log.LOCAL_ADDR
     *
     * @return the value of sys_request_log.LOCAL_ADDR
     *
     * @mbggenerated Tue Mar 14 11:46:38 CST 2017
     */
    public String getLocalAddr() {
        return localAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_request_log.LOCAL_ADDR
     *
     * @param localAddr the value for sys_request_log.LOCAL_ADDR
     *
     * @mbggenerated Tue Mar 14 11:46:38 CST 2017
     */
    public void setLocalAddr(String localAddr) {
        this.localAddr = localAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_request_log.LOCAL_NAME
     *
     * @return the value of sys_request_log.LOCAL_NAME
     *
     * @mbggenerated Tue Mar 14 11:46:38 CST 2017
     */
    public String getLocalName() {
        return localName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_request_log.LOCAL_NAME
     *
     * @param localName the value for sys_request_log.LOCAL_NAME
     *
     * @mbggenerated Tue Mar 14 11:46:38 CST 2017
     */
    public void setLocalName(String localName) {
        this.localName = localName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_request_log.LOCAL_PORT
     *
     * @return the value of sys_request_log.LOCAL_PORT
     *
     * @mbggenerated Tue Mar 14 11:46:38 CST 2017
     */
    public Integer getLocalPort() {
        return localPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_request_log.LOCAL_PORT
     *
     * @param localPort the value for sys_request_log.LOCAL_PORT
     *
     * @mbggenerated Tue Mar 14 11:46:38 CST 2017
     */
    public void setLocalPort(Integer localPort) {
        this.localPort = localPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_request_log.JVM_MAX_MEMORY
     *
     * @return the value of sys_request_log.JVM_MAX_MEMORY
     *
     * @mbggenerated Tue Mar 14 11:46:38 CST 2017
     */
    public Integer getJvmMaxMemory() {
        return jvmMaxMemory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_request_log.JVM_MAX_MEMORY
     *
     * @param jvmMaxMemory the value for sys_request_log.JVM_MAX_MEMORY
     *
     * @mbggenerated Tue Mar 14 11:46:38 CST 2017
     */
    public void setJvmMaxMemory(Integer jvmMaxMemory) {
        this.jvmMaxMemory = jvmMaxMemory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_request_log.JVM_TOTAL_MEMORY
     *
     * @return the value of sys_request_log.JVM_TOTAL_MEMORY
     *
     * @mbggenerated Tue Mar 14 11:46:38 CST 2017
     */
    public Integer getJvmTotalMemory() {
        return jvmTotalMemory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_request_log.JVM_TOTAL_MEMORY
     *
     * @param jvmTotalMemory the value for sys_request_log.JVM_TOTAL_MEMORY
     *
     * @mbggenerated Tue Mar 14 11:46:38 CST 2017
     */
    public void setJvmTotalMemory(Integer jvmTotalMemory) {
        this.jvmTotalMemory = jvmTotalMemory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_request_log.JVM_FREE_MEMORY
     *
     * @return the value of sys_request_log.JVM_FREE_MEMORY
     *
     * @mbggenerated Tue Mar 14 11:46:38 CST 2017
     */
    public Integer getJvmFreeMemory() {
        return jvmFreeMemory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_request_log.JVM_FREE_MEMORY
     *
     * @param jvmFreeMemory the value for sys_request_log.JVM_FREE_MEMORY
     *
     * @mbggenerated Tue Mar 14 11:46:38 CST 2017
     */
    public void setJvmFreeMemory(Integer jvmFreeMemory) {
        this.jvmFreeMemory = jvmFreeMemory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_request_log.JVM_USER_MEMORY
     *
     * @return the value of sys_request_log.JVM_USER_MEMORY
     *
     * @mbggenerated Tue Mar 14 11:46:38 CST 2017
     */
    public Integer getJvmUserMemory() {
        return jvmUserMemory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_request_log.JVM_USER_MEMORY
     *
     * @param jvmUserMemory the value for sys_request_log.JVM_USER_MEMORY
     *
     * @mbggenerated Tue Mar 14 11:46:38 CST 2017
     */
    public void setJvmUserMemory(Integer jvmUserMemory) {
        this.jvmUserMemory = jvmUserMemory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_request_log.CREATE_DATE
     *
     * @return the value of sys_request_log.CREATE_DATE
     *
     * @mbggenerated Tue Mar 14 11:46:38 CST 2017
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_request_log.CREATE_DATE
     *
     * @param createDate the value for sys_request_log.CREATE_DATE
     *
     * @mbggenerated Tue Mar 14 11:46:38 CST 2017
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_request_log
     *
     * @mbggenerated Tue Mar 14 11:46:38 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SysRequestLog other = (SysRequestLog) that;
        return (this.getLogId() == null ? other.getLogId() == null : this.getLogId().equals(other.getLogId()))
            && (this.getBeginTime() == null ? other.getBeginTime() == null : this.getBeginTime().equals(other.getBeginTime()))
            && (this.getEndTime() == null ? other.getEndTime() == null : this.getEndTime().equals(other.getEndTime()))
            && (this.getRequestTime() == null ? other.getRequestTime() == null : this.getRequestTime().equals(other.getRequestTime()))
            && (this.getLoginName() == null ? other.getLoginName() == null : this.getLoginName().equals(other.getLoginName()))
            && (this.getSessionId() == null ? other.getSessionId() == null : this.getSessionId().equals(other.getSessionId()))
            && (this.getScheme() == null ? other.getScheme() == null : this.getScheme().equals(other.getScheme()))
            && (this.getServerName() == null ? other.getServerName() == null : this.getServerName().equals(other.getServerName()))
            && (this.getServerPort() == null ? other.getServerPort() == null : this.getServerPort().equals(other.getServerPort()))
            && (this.getRequestUri() == null ? other.getRequestUri() == null : this.getRequestUri().equals(other.getRequestUri()))
            && (this.getMethod() == null ? other.getMethod() == null : this.getMethod().equals(other.getMethod()))
            && (this.getRequestParams() == null ? other.getRequestParams() == null : this.getRequestParams().equals(other.getRequestParams()))
            && (this.getMobilePat() == null ? other.getMobilePat() == null : this.getMobilePat().equals(other.getMobilePat()))
            && (this.getCharacterEncoding() == null ? other.getCharacterEncoding() == null : this.getCharacterEncoding().equals(other.getCharacterEncoding()))
            && (this.getContentLength() == null ? other.getContentLength() == null : this.getContentLength().equals(other.getContentLength()))
            && (this.getLocalAddr() == null ? other.getLocalAddr() == null : this.getLocalAddr().equals(other.getLocalAddr()))
            && (this.getLocalName() == null ? other.getLocalName() == null : this.getLocalName().equals(other.getLocalName()))
            && (this.getLocalPort() == null ? other.getLocalPort() == null : this.getLocalPort().equals(other.getLocalPort()))
            && (this.getJvmMaxMemory() == null ? other.getJvmMaxMemory() == null : this.getJvmMaxMemory().equals(other.getJvmMaxMemory()))
            && (this.getJvmTotalMemory() == null ? other.getJvmTotalMemory() == null : this.getJvmTotalMemory().equals(other.getJvmTotalMemory()))
            && (this.getJvmFreeMemory() == null ? other.getJvmFreeMemory() == null : this.getJvmFreeMemory().equals(other.getJvmFreeMemory()))
            && (this.getJvmUserMemory() == null ? other.getJvmUserMemory() == null : this.getJvmUserMemory().equals(other.getJvmUserMemory()))
            && (this.getCreateDate() == null ? other.getCreateDate() == null : this.getCreateDate().equals(other.getCreateDate()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_request_log
     *
     * @mbggenerated Tue Mar 14 11:46:38 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getLogId() == null) ? 0 : getLogId().hashCode());
        result = prime * result + ((getBeginTime() == null) ? 0 : getBeginTime().hashCode());
        result = prime * result + ((getEndTime() == null) ? 0 : getEndTime().hashCode());
        result = prime * result + ((getRequestTime() == null) ? 0 : getRequestTime().hashCode());
        result = prime * result + ((getLoginName() == null) ? 0 : getLoginName().hashCode());
        result = prime * result + ((getSessionId() == null) ? 0 : getSessionId().hashCode());
        result = prime * result + ((getScheme() == null) ? 0 : getScheme().hashCode());
        result = prime * result + ((getServerName() == null) ? 0 : getServerName().hashCode());
        result = prime * result + ((getServerPort() == null) ? 0 : getServerPort().hashCode());
        result = prime * result + ((getRequestUri() == null) ? 0 : getRequestUri().hashCode());
        result = prime * result + ((getMethod() == null) ? 0 : getMethod().hashCode());
        result = prime * result + ((getRequestParams() == null) ? 0 : getRequestParams().hashCode());
        result = prime * result + ((getMobilePat() == null) ? 0 : getMobilePat().hashCode());
        result = prime * result + ((getCharacterEncoding() == null) ? 0 : getCharacterEncoding().hashCode());
        result = prime * result + ((getContentLength() == null) ? 0 : getContentLength().hashCode());
        result = prime * result + ((getLocalAddr() == null) ? 0 : getLocalAddr().hashCode());
        result = prime * result + ((getLocalName() == null) ? 0 : getLocalName().hashCode());
        result = prime * result + ((getLocalPort() == null) ? 0 : getLocalPort().hashCode());
        result = prime * result + ((getJvmMaxMemory() == null) ? 0 : getJvmMaxMemory().hashCode());
        result = prime * result + ((getJvmTotalMemory() == null) ? 0 : getJvmTotalMemory().hashCode());
        result = prime * result + ((getJvmFreeMemory() == null) ? 0 : getJvmFreeMemory().hashCode());
        result = prime * result + ((getJvmUserMemory() == null) ? 0 : getJvmUserMemory().hashCode());
        result = prime * result + ((getCreateDate() == null) ? 0 : getCreateDate().hashCode());
        return result;
    }
}
