package com.fh.entity.organization;

import java.io.Serializable;
import java.util.Date;

public class BaseDealer implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_dealer.DEALER_ID
     *
     * @mbggenerated Wed Apr 12 18:18:24 CST 2017
     */
    private Long dealerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_dealer.O_ORG_ID
     *
     * @mbggenerated Wed Apr 12 18:18:24 CST 2017
     */
    private Long oOrgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_dealer.O_ORG_CODE
     *
     * @mbggenerated Wed Apr 12 18:18:24 CST 2017
     */
    private String oOrgCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_dealer.O_ORG_NAME
     *
     * @mbggenerated Wed Apr 12 18:18:24 CST 2017
     */
    private String oOrgName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_dealer.T_ORG_ID
     *
     * @mbggenerated Wed Apr 12 18:18:24 CST 2017
     */
    private Long tOrgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_dealer.T_ORG_CODE
     *
     * @mbggenerated Wed Apr 12 18:18:24 CST 2017
     */
    private String tOrgCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_dealer.T_ORG_NAME
     *
     * @mbggenerated Wed Apr 12 18:18:24 CST 2017
     */
    private String tOrgName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_dealer.ORG_NAME
     *
     * @mbggenerated Wed Apr 12 18:18:24 CST 2017
     */
    private String orgName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_dealer.ORG_ID
     *
     * @mbggenerated Wed Apr 12 18:18:24 CST 2017
     */
    private Long orgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_dealer.ORG_CODE
     *
     * @mbggenerated Wed Apr 12 18:18:24 CST 2017
     */
    private String orgCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_dealer.DEALER_CODE
     *
     * @mbggenerated Wed Apr 12 18:18:24 CST 2017
     */
    private String dealerCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_dealer.DEALER_NAME
     *
     * @mbggenerated Wed Apr 12 18:18:24 CST 2017
     */
    private String dealerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_dealer.LINKMAN
     *
     * @mbggenerated Wed Apr 12 18:18:24 CST 2017
     */
    private String linkman;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_dealer.LINKTEL
     *
     * @mbggenerated Wed Apr 12 18:18:24 CST 2017
     */
    private String linktel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_dealer.EMAIL
     *
     * @mbggenerated Wed Apr 12 18:18:24 CST 2017
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_dealer.FAX
     *
     * @mbggenerated Wed Apr 12 18:18:24 CST 2017
     */
    private String fax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_dealer.HELP_TEL
     *
     * @mbggenerated Wed Apr 12 18:18:24 CST 2017
     */
    private String helpTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_dealer.ORDER_TEL
     *
     * @mbggenerated Wed Apr 12 18:18:24 CST 2017
     */
    private String orderTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_dealer.ADDRESS
     *
     * @mbggenerated Wed Apr 12 18:18:24 CST 2017
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_dealer.LONGITUDE
     *
     * @mbggenerated Wed Apr 12 18:18:24 CST 2017
     */
    private String longitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_dealer.LATITUDE
     *
     * @mbggenerated Wed Apr 12 18:18:24 CST 2017
     */
    private String latitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_dealer.STATUS
     *
     * @mbggenerated Wed Apr 12 18:18:24 CST 2017
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_dealer.ORDER_DISCOUNT
     *
     * @mbggenerated Wed Apr 12 18:18:24 CST 2017
     */
    private String orderDiscount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_dealer.QRCODE_URL
     *
     * @mbggenerated Wed Apr 12 18:18:24 CST 2017
     */
    private String qrcodeUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_dealer.APP_ID
     *
     * @mbggenerated Wed Apr 12 18:18:24 CST 2017
     */
    private String appId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_dealer.APPSECRET
     *
     * @mbggenerated Wed Apr 12 18:18:24 CST 2017
     */
    private String appsecret;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_dealer.TOKEN
     *
     * @mbggenerated Wed Apr 12 18:18:24 CST 2017
     */
    private String token;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_dealer.WECHAT_ID
     *
     * @mbggenerated Wed Apr 12 18:18:24 CST 2017
     */
    private String wechatId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_dealer.COMPANY_INFO
     *
     * @mbggenerated Wed Apr 12 18:18:24 CST 2017
     */
    private String companyInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_dealer.ACCESSTOKEN
     *
     * @mbggenerated Wed Apr 12 18:18:24 CST 2017
     */
    private String accesstoken;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_dealer.TOKEN_TIME
     *
     * @mbggenerated Wed Apr 12 18:18:24 CST 2017
     */
    private Date tokenTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_dealer.TICKET_TIME
     *
     * @mbggenerated Wed Apr 12 18:18:24 CST 2017
     */
    private Date ticketTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_dealer.JSAPI_TICKET
     *
     * @mbggenerated Wed Apr 12 18:18:24 CST 2017
     */
    private String jsapiTicket;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_dealer.WECHAT_MENU_STATUS
     *
     * @mbggenerated Wed Apr 12 18:18:24 CST 2017
     */
    private Integer wechatMenuStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_dealer.WECHAT_MENU_TIME
     *
     * @mbggenerated Wed Apr 12 18:18:24 CST 2017
     */
    private Date wechatMenuTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_dealer.CREATE_BY
     *
     * @mbggenerated Wed Apr 12 18:18:24 CST 2017
     */
    private String createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_dealer.CREATE_DATE
     *
     * @mbggenerated Wed Apr 12 18:18:24 CST 2017
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_dealer.UPDATE_BY
     *
     * @mbggenerated Wed Apr 12 18:18:24 CST 2017
     */
    private String updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_dealer.UPDATE_DATE
     *
     * @mbggenerated Wed Apr 12 18:18:24 CST 2017
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_dealer.WORK_BEGIN
     *
     * @mbggenerated Wed Apr 12 18:18:24 CST 2017
     */
    private String workBegin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_dealer.WORK_END
     *
     * @mbggenerated Wed Apr 12 18:18:24 CST 2017
     */
    private String workEnd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table base_dealer
     *
     * @mbggenerated Wed Apr 12 18:18:24 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_dealer.DEALER_ID
     *
     * @return the value of base_dealer.DEALER_ID
     *
     * @mbggenerated Wed Apr 12 18:18:24 CST 2017
     */
    public Long getDealerId() {
        return dealerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_dealer.DEALER_ID
     *
     * @param dealerId the value for base_dealer.DEALER_ID
     *
     * @mbggenerated Wed Apr 12 18:18:24 CST 2017
     */
    public void setDealerId(Long dealerId) {
        this.dealerId = dealerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_dealer.O_ORG_ID
     *
     * @return the value of base_dealer.O_ORG_ID
     *
     * @mbggenerated Wed Apr 12 18:18:24 CST 2017
     */
    public Long getoOrgId() {
        return oOrgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_dealer.O_ORG_ID
     *
     * @param oOrgId the value for base_dealer.O_ORG_ID
     *
     * @mbggenerated Wed Apr 12 18:18:24 CST 2017
     */
    public void setoOrgId(Long oOrgId) {
        this.oOrgId = oOrgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_dealer.O_ORG_CODE
     *
     * @return the value of base_dealer.O_ORG_CODE
     *
     * @mbggenerated Wed Apr 12 18:18:24 CST 2017
     */
    public String getoOrgCode() {
        return oOrgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_dealer.O_ORG_CODE
     *
     * @param oOrgCode the value for base_dealer.O_ORG_CODE
     *
     * @mbggenerated Wed Apr 12 18:18:24 CST 2017
     */
    public void setoOrgCode(String oOrgCode) {
        this.oOrgCode = oOrgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_dealer.O_ORG_NAME
     *
     * @return the value of base_dealer.O_ORG_NAME
     *
     * @mbggenerated Wed Apr 12 18:18:24 CST 2017
     */
    public String getoOrgName() {
        return oOrgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_dealer.O_ORG_NAME
     *
     * @param oOrgName the value for base_dealer.O_ORG_NAME
     *
     * @mbggenerated Wed Apr 12 18:18:24 CST 2017
     */
    public void setoOrgName(String oOrgName) {
        this.oOrgName = oOrgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_dealer.T_ORG_ID
     *
     * @return the value of base_dealer.T_ORG_ID
     *
     * @mbggenerated Wed Apr 12 18:18:24 CST 2017
     */
    public Long gettOrgId() {
        return tOrgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_dealer.T_ORG_ID
     *
     * @param tOrgId the value for base_dealer.T_ORG_ID
     *
     * @mbggenerated Wed Apr 12 18:18:24 CST 2017
     */
    public void settOrgId(Long tOrgId) {
        this.tOrgId = tOrgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_dealer.T_ORG_CODE
     *
     * @return the value of base_dealer.T_ORG_CODE
     *
     * @mbggenerated Wed Apr 12 18:18:24 CST 2017
     */
    public String gettOrgCode() {
        return tOrgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_dealer.T_ORG_CODE
     *
     * @param tOrgCode the value for base_dealer.T_ORG_CODE
     *
     * @mbggenerated Wed Apr 12 18:18:24 CST 2017
     */
    public void settOrgCode(String tOrgCode) {
        this.tOrgCode = tOrgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_dealer.T_ORG_NAME
     *
     * @return the value of base_dealer.T_ORG_NAME
     *
     * @mbggenerated Wed Apr 12 18:18:24 CST 2017
     */
    public String gettOrgName() {
        return tOrgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_dealer.T_ORG_NAME
     *
     * @param tOrgName the value for base_dealer.T_ORG_NAME
     *
     * @mbggenerated Wed Apr 12 18:18:24 CST 2017
     */
    public void settOrgName(String tOrgName) {
        this.tOrgName = tOrgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_dealer.ORG_NAME
     *
     * @return the value of base_dealer.ORG_NAME
     *
     * @mbggenerated Wed Apr 12 18:18:24 CST 2017
     */
    public String getOrgName() {
        return orgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_dealer.ORG_NAME
     *
     * @param orgName the value for base_dealer.ORG_NAME
     *
     * @mbggenerated Wed Apr 12 18:18:24 CST 2017
     */
    public void setOrgName(String orgName) {
        this.orgName = orgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_dealer.ORG_ID
     *
     * @return the value of base_dealer.ORG_ID
     *
     * @mbggenerated Wed Apr 12 18:18:24 CST 2017
     */
    public Long getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_dealer.ORG_ID
     *
     * @param orgId the value for base_dealer.ORG_ID
     *
     * @mbggenerated Wed Apr 12 18:18:24 CST 2017
     */
    public void setOrgId(Long orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_dealer.ORG_CODE
     *
     * @return the value of base_dealer.ORG_CODE
     *
     * @mbggenerated Wed Apr 12 18:18:24 CST 2017
     */
    public String getOrgCode() {
        return orgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_dealer.ORG_CODE
     *
     * @param orgCode the value for base_dealer.ORG_CODE
     *
     * @mbggenerated Wed Apr 12 18:18:24 CST 2017
     */
    public void setOrgCode(String orgCode) {
        this.orgCode = orgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_dealer.DEALER_CODE
     *
     * @return the value of base_dealer.DEALER_CODE
     *
     * @mbggenerated Wed Apr 12 18:18:24 CST 2017
     */
    public String getDealerCode() {
        return dealerCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_dealer.DEALER_CODE
     *
     * @param dealerCode the value for base_dealer.DEALER_CODE
     *
     * @mbggenerated Wed Apr 12 18:18:24 CST 2017
     */
    public void setDealerCode(String dealerCode) {
        this.dealerCode = dealerCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_dealer.DEALER_NAME
     *
     * @return the value of base_dealer.DEALER_NAME
     *
     * @mbggenerated Wed Apr 12 18:18:24 CST 2017
     */
    public String getDealerName() {
        return dealerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_dealer.DEALER_NAME
     *
     * @param dealerName the value for base_dealer.DEALER_NAME
     *
     * @mbggenerated Wed Apr 12 18:18:24 CST 2017
     */
    public void setDealerName(String dealerName) {
        this.dealerName = dealerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_dealer.LINKMAN
     *
     * @return the value of base_dealer.LINKMAN
     *
     * @mbggenerated Wed Apr 12 18:18:24 CST 2017
     */
    public String getLinkman() {
        return linkman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_dealer.LINKMAN
     *
     * @param linkman the value for base_dealer.LINKMAN
     *
     * @mbggenerated Wed Apr 12 18:18:24 CST 2017
     */
    public void setLinkman(String linkman) {
        this.linkman = linkman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_dealer.LINKTEL
     *
     * @return the value of base_dealer.LINKTEL
     *
     * @mbggenerated Wed Apr 12 18:18:24 CST 2017
     */
    public String getLinktel() {
        return linktel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_dealer.LINKTEL
     *
     * @param linktel the value for base_dealer.LINKTEL
     *
     * @mbggenerated Wed Apr 12 18:18:24 CST 2017
     */
    public void setLinktel(String linktel) {
        this.linktel = linktel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_dealer.EMAIL
     *
     * @return the value of base_dealer.EMAIL
     *
     * @mbggenerated Wed Apr 12 18:18:24 CST 2017
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_dealer.EMAIL
     *
     * @param email the value for base_dealer.EMAIL
     *
     * @mbggenerated Wed Apr 12 18:18:24 CST 2017
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_dealer.FAX
     *
     * @return the value of base_dealer.FAX
     *
     * @mbggenerated Wed Apr 12 18:18:24 CST 2017
     */
    public String getFax() {
        return fax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_dealer.FAX
     *
     * @param fax the value for base_dealer.FAX
     *
     * @mbggenerated Wed Apr 12 18:18:24 CST 2017
     */
    public void setFax(String fax) {
        this.fax = fax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_dealer.HELP_TEL
     *
     * @return the value of base_dealer.HELP_TEL
     *
     * @mbggenerated Wed Apr 12 18:18:24 CST 2017
     */
    public String getHelpTel() {
        return helpTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_dealer.HELP_TEL
     *
     * @param helpTel the value for base_dealer.HELP_TEL
     *
     * @mbggenerated Wed Apr 12 18:18:24 CST 2017
     */
    public void setHelpTel(String helpTel) {
        this.helpTel = helpTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_dealer.ORDER_TEL
     *
     * @return the value of base_dealer.ORDER_TEL
     *
     * @mbggenerated Wed Apr 12 18:18:24 CST 2017
     */
    public String getOrderTel() {
        return orderTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_dealer.ORDER_TEL
     *
     * @param orderTel the value for base_dealer.ORDER_TEL
     *
     * @mbggenerated Wed Apr 12 18:18:24 CST 2017
     */
    public void setOrderTel(String orderTel) {
        this.orderTel = orderTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_dealer.ADDRESS
     *
     * @return the value of base_dealer.ADDRESS
     *
     * @mbggenerated Wed Apr 12 18:18:24 CST 2017
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_dealer.ADDRESS
     *
     * @param address the value for base_dealer.ADDRESS
     *
     * @mbggenerated Wed Apr 12 18:18:24 CST 2017
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_dealer.LONGITUDE
     *
     * @return the value of base_dealer.LONGITUDE
     *
     * @mbggenerated Wed Apr 12 18:18:24 CST 2017
     */
    public String getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_dealer.LONGITUDE
     *
     * @param longitude the value for base_dealer.LONGITUDE
     *
     * @mbggenerated Wed Apr 12 18:18:24 CST 2017
     */
    public void setLongitude(String longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_dealer.LATITUDE
     *
     * @return the value of base_dealer.LATITUDE
     *
     * @mbggenerated Wed Apr 12 18:18:24 CST 2017
     */
    public String getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_dealer.LATITUDE
     *
     * @param latitude the value for base_dealer.LATITUDE
     *
     * @mbggenerated Wed Apr 12 18:18:24 CST 2017
     */
    public void setLatitude(String latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_dealer.STATUS
     *
     * @return the value of base_dealer.STATUS
     *
     * @mbggenerated Wed Apr 12 18:18:24 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_dealer.STATUS
     *
     * @param status the value for base_dealer.STATUS
     *
     * @mbggenerated Wed Apr 12 18:18:24 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_dealer.ORDER_DISCOUNT
     *
     * @return the value of base_dealer.ORDER_DISCOUNT
     *
     * @mbggenerated Wed Apr 12 18:18:24 CST 2017
     */
    public String getOrderDiscount() {
        return orderDiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_dealer.ORDER_DISCOUNT
     *
     * @param orderDiscount the value for base_dealer.ORDER_DISCOUNT
     *
     * @mbggenerated Wed Apr 12 18:18:24 CST 2017
     */
    public void setOrderDiscount(String orderDiscount) {
        this.orderDiscount = orderDiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_dealer.QRCODE_URL
     *
     * @return the value of base_dealer.QRCODE_URL
     *
     * @mbggenerated Wed Apr 12 18:18:24 CST 2017
     */
    public String getQrcodeUrl() {
        return qrcodeUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_dealer.QRCODE_URL
     *
     * @param qrcodeUrl the value for base_dealer.QRCODE_URL
     *
     * @mbggenerated Wed Apr 12 18:18:24 CST 2017
     */
    public void setQrcodeUrl(String qrcodeUrl) {
        this.qrcodeUrl = qrcodeUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_dealer.APP_ID
     *
     * @return the value of base_dealer.APP_ID
     *
     * @mbggenerated Wed Apr 12 18:18:24 CST 2017
     */
    public String getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_dealer.APP_ID
     *
     * @param appId the value for base_dealer.APP_ID
     *
     * @mbggenerated Wed Apr 12 18:18:24 CST 2017
     */
    public void setAppId(String appId) {
        this.appId = appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_dealer.APPSECRET
     *
     * @return the value of base_dealer.APPSECRET
     *
     * @mbggenerated Wed Apr 12 18:18:24 CST 2017
     */
    public String getAppsecret() {
        return appsecret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_dealer.APPSECRET
     *
     * @param appsecret the value for base_dealer.APPSECRET
     *
     * @mbggenerated Wed Apr 12 18:18:24 CST 2017
     */
    public void setAppsecret(String appsecret) {
        this.appsecret = appsecret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_dealer.TOKEN
     *
     * @return the value of base_dealer.TOKEN
     *
     * @mbggenerated Wed Apr 12 18:18:24 CST 2017
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_dealer.TOKEN
     *
     * @param token the value for base_dealer.TOKEN
     *
     * @mbggenerated Wed Apr 12 18:18:24 CST 2017
     */
    public void setToken(String token) {
        this.token = token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_dealer.WECHAT_ID
     *
     * @return the value of base_dealer.WECHAT_ID
     *
     * @mbggenerated Wed Apr 12 18:18:24 CST 2017
     */
    public String getWechatId() {
        return wechatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_dealer.WECHAT_ID
     *
     * @param wechatId the value for base_dealer.WECHAT_ID
     *
     * @mbggenerated Wed Apr 12 18:18:24 CST 2017
     */
    public void setWechatId(String wechatId) {
        this.wechatId = wechatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_dealer.COMPANY_INFO
     *
     * @return the value of base_dealer.COMPANY_INFO
     *
     * @mbggenerated Wed Apr 12 18:18:24 CST 2017
     */
    public String getCompanyInfo() {
        return companyInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_dealer.COMPANY_INFO
     *
     * @param companyInfo the value for base_dealer.COMPANY_INFO
     *
     * @mbggenerated Wed Apr 12 18:18:24 CST 2017
     */
    public void setCompanyInfo(String companyInfo) {
        this.companyInfo = companyInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_dealer.ACCESSTOKEN
     *
     * @return the value of base_dealer.ACCESSTOKEN
     *
     * @mbggenerated Wed Apr 12 18:18:24 CST 2017
     */
    public String getAccesstoken() {
        return accesstoken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_dealer.ACCESSTOKEN
     *
     * @param accesstoken the value for base_dealer.ACCESSTOKEN
     *
     * @mbggenerated Wed Apr 12 18:18:24 CST 2017
     */
    public void setAccesstoken(String accesstoken) {
        this.accesstoken = accesstoken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_dealer.TOKEN_TIME
     *
     * @return the value of base_dealer.TOKEN_TIME
     *
     * @mbggenerated Wed Apr 12 18:18:24 CST 2017
     */
    public Date getTokenTime() {
        return tokenTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_dealer.TOKEN_TIME
     *
     * @param tokenTime the value for base_dealer.TOKEN_TIME
     *
     * @mbggenerated Wed Apr 12 18:18:24 CST 2017
     */
    public void setTokenTime(Date tokenTime) {
        this.tokenTime = tokenTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_dealer.TICKET_TIME
     *
     * @return the value of base_dealer.TICKET_TIME
     *
     * @mbggenerated Wed Apr 12 18:18:24 CST 2017
     */
    public Date getTicketTime() {
        return ticketTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_dealer.TICKET_TIME
     *
     * @param ticketTime the value for base_dealer.TICKET_TIME
     *
     * @mbggenerated Wed Apr 12 18:18:24 CST 2017
     */
    public void setTicketTime(Date ticketTime) {
        this.ticketTime = ticketTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_dealer.JSAPI_TICKET
     *
     * @return the value of base_dealer.JSAPI_TICKET
     *
     * @mbggenerated Wed Apr 12 18:18:24 CST 2017
     */
    public String getJsapiTicket() {
        return jsapiTicket;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_dealer.JSAPI_TICKET
     *
     * @param jsapiTicket the value for base_dealer.JSAPI_TICKET
     *
     * @mbggenerated Wed Apr 12 18:18:24 CST 2017
     */
    public void setJsapiTicket(String jsapiTicket) {
        this.jsapiTicket = jsapiTicket;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_dealer.WECHAT_MENU_STATUS
     *
     * @return the value of base_dealer.WECHAT_MENU_STATUS
     *
     * @mbggenerated Wed Apr 12 18:18:24 CST 2017
     */
    public Integer getWechatMenuStatus() {
        return wechatMenuStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_dealer.WECHAT_MENU_STATUS
     *
     * @param wechatMenuStatus the value for base_dealer.WECHAT_MENU_STATUS
     *
     * @mbggenerated Wed Apr 12 18:18:24 CST 2017
     */
    public void setWechatMenuStatus(Integer wechatMenuStatus) {
        this.wechatMenuStatus = wechatMenuStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_dealer.WECHAT_MENU_TIME
     *
     * @return the value of base_dealer.WECHAT_MENU_TIME
     *
     * @mbggenerated Wed Apr 12 18:18:24 CST 2017
     */
    public Date getWechatMenuTime() {
        return wechatMenuTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_dealer.WECHAT_MENU_TIME
     *
     * @param wechatMenuTime the value for base_dealer.WECHAT_MENU_TIME
     *
     * @mbggenerated Wed Apr 12 18:18:24 CST 2017
     */
    public void setWechatMenuTime(Date wechatMenuTime) {
        this.wechatMenuTime = wechatMenuTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_dealer.CREATE_BY
     *
     * @return the value of base_dealer.CREATE_BY
     *
     * @mbggenerated Wed Apr 12 18:18:24 CST 2017
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_dealer.CREATE_BY
     *
     * @param createBy the value for base_dealer.CREATE_BY
     *
     * @mbggenerated Wed Apr 12 18:18:24 CST 2017
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_dealer.CREATE_DATE
     *
     * @return the value of base_dealer.CREATE_DATE
     *
     * @mbggenerated Wed Apr 12 18:18:24 CST 2017
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_dealer.CREATE_DATE
     *
     * @param createDate the value for base_dealer.CREATE_DATE
     *
     * @mbggenerated Wed Apr 12 18:18:24 CST 2017
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_dealer.UPDATE_BY
     *
     * @return the value of base_dealer.UPDATE_BY
     *
     * @mbggenerated Wed Apr 12 18:18:24 CST 2017
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_dealer.UPDATE_BY
     *
     * @param updateBy the value for base_dealer.UPDATE_BY
     *
     * @mbggenerated Wed Apr 12 18:18:24 CST 2017
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_dealer.UPDATE_DATE
     *
     * @return the value of base_dealer.UPDATE_DATE
     *
     * @mbggenerated Wed Apr 12 18:18:24 CST 2017
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_dealer.UPDATE_DATE
     *
     * @param updateDate the value for base_dealer.UPDATE_DATE
     *
     * @mbggenerated Wed Apr 12 18:18:24 CST 2017
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_dealer.WORK_BEGIN
     *
     * @return the value of base_dealer.WORK_BEGIN
     *
     * @mbggenerated Wed Apr 12 18:18:24 CST 2017
     */
    public String getWorkBegin() {
        return workBegin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_dealer.WORK_BEGIN
     *
     * @param workBegin the value for base_dealer.WORK_BEGIN
     *
     * @mbggenerated Wed Apr 12 18:18:24 CST 2017
     */
    public void setWorkBegin(String workBegin) {
        this.workBegin = workBegin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_dealer.WORK_END
     *
     * @return the value of base_dealer.WORK_END
     *
     * @mbggenerated Wed Apr 12 18:18:24 CST 2017
     */
    public String getWorkEnd() {
        return workEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_dealer.WORK_END
     *
     * @param workEnd the value for base_dealer.WORK_END
     *
     * @mbggenerated Wed Apr 12 18:18:24 CST 2017
     */
    public void setWorkEnd(String workEnd) {
        this.workEnd = workEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_dealer
     *
     * @mbggenerated Wed Apr 12 18:18:24 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        BaseDealer other = (BaseDealer) that;
        return (this.getDealerId() == null ? other.getDealerId() == null : this.getDealerId().equals(other.getDealerId()))
            && (this.getoOrgId() == null ? other.getoOrgId() == null : this.getoOrgId().equals(other.getoOrgId()))
            && (this.getoOrgCode() == null ? other.getoOrgCode() == null : this.getoOrgCode().equals(other.getoOrgCode()))
            && (this.getoOrgName() == null ? other.getoOrgName() == null : this.getoOrgName().equals(other.getoOrgName()))
            && (this.gettOrgId() == null ? other.gettOrgId() == null : this.gettOrgId().equals(other.gettOrgId()))
            && (this.gettOrgCode() == null ? other.gettOrgCode() == null : this.gettOrgCode().equals(other.gettOrgCode()))
            && (this.gettOrgName() == null ? other.gettOrgName() == null : this.gettOrgName().equals(other.gettOrgName()))
            && (this.getOrgName() == null ? other.getOrgName() == null : this.getOrgName().equals(other.getOrgName()))
            && (this.getOrgId() == null ? other.getOrgId() == null : this.getOrgId().equals(other.getOrgId()))
            && (this.getOrgCode() == null ? other.getOrgCode() == null : this.getOrgCode().equals(other.getOrgCode()))
            && (this.getDealerCode() == null ? other.getDealerCode() == null : this.getDealerCode().equals(other.getDealerCode()))
            && (this.getDealerName() == null ? other.getDealerName() == null : this.getDealerName().equals(other.getDealerName()))
            && (this.getLinkman() == null ? other.getLinkman() == null : this.getLinkman().equals(other.getLinkman()))
            && (this.getLinktel() == null ? other.getLinktel() == null : this.getLinktel().equals(other.getLinktel()))
            && (this.getEmail() == null ? other.getEmail() == null : this.getEmail().equals(other.getEmail()))
            && (this.getFax() == null ? other.getFax() == null : this.getFax().equals(other.getFax()))
            && (this.getHelpTel() == null ? other.getHelpTel() == null : this.getHelpTel().equals(other.getHelpTel()))
            && (this.getOrderTel() == null ? other.getOrderTel() == null : this.getOrderTel().equals(other.getOrderTel()))
            && (this.getAddress() == null ? other.getAddress() == null : this.getAddress().equals(other.getAddress()))
            && (this.getLongitude() == null ? other.getLongitude() == null : this.getLongitude().equals(other.getLongitude()))
            && (this.getLatitude() == null ? other.getLatitude() == null : this.getLatitude().equals(other.getLatitude()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getOrderDiscount() == null ? other.getOrderDiscount() == null : this.getOrderDiscount().equals(other.getOrderDiscount()))
            && (this.getQrcodeUrl() == null ? other.getQrcodeUrl() == null : this.getQrcodeUrl().equals(other.getQrcodeUrl()))
            && (this.getAppId() == null ? other.getAppId() == null : this.getAppId().equals(other.getAppId()))
            && (this.getAppsecret() == null ? other.getAppsecret() == null : this.getAppsecret().equals(other.getAppsecret()))
            && (this.getToken() == null ? other.getToken() == null : this.getToken().equals(other.getToken()))
            && (this.getWechatId() == null ? other.getWechatId() == null : this.getWechatId().equals(other.getWechatId()))
            && (this.getCompanyInfo() == null ? other.getCompanyInfo() == null : this.getCompanyInfo().equals(other.getCompanyInfo()))
            && (this.getAccesstoken() == null ? other.getAccesstoken() == null : this.getAccesstoken().equals(other.getAccesstoken()))
            && (this.getTokenTime() == null ? other.getTokenTime() == null : this.getTokenTime().equals(other.getTokenTime()))
            && (this.getTicketTime() == null ? other.getTicketTime() == null : this.getTicketTime().equals(other.getTicketTime()))
            && (this.getJsapiTicket() == null ? other.getJsapiTicket() == null : this.getJsapiTicket().equals(other.getJsapiTicket()))
            && (this.getWechatMenuStatus() == null ? other.getWechatMenuStatus() == null : this.getWechatMenuStatus().equals(other.getWechatMenuStatus()))
            && (this.getWechatMenuTime() == null ? other.getWechatMenuTime() == null : this.getWechatMenuTime().equals(other.getWechatMenuTime()))
            && (this.getCreateBy() == null ? other.getCreateBy() == null : this.getCreateBy().equals(other.getCreateBy()))
            && (this.getCreateDate() == null ? other.getCreateDate() == null : this.getCreateDate().equals(other.getCreateDate()))
            && (this.getUpdateBy() == null ? other.getUpdateBy() == null : this.getUpdateBy().equals(other.getUpdateBy()))
            && (this.getUpdateDate() == null ? other.getUpdateDate() == null : this.getUpdateDate().equals(other.getUpdateDate()))
            && (this.getWorkBegin() == null ? other.getWorkBegin() == null : this.getWorkBegin().equals(other.getWorkBegin()))
            && (this.getWorkEnd() == null ? other.getWorkEnd() == null : this.getWorkEnd().equals(other.getWorkEnd()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_dealer
     *
     * @mbggenerated Wed Apr 12 18:18:24 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getDealerId() == null) ? 0 : getDealerId().hashCode());
        result = prime * result + ((getoOrgId() == null) ? 0 : getoOrgId().hashCode());
        result = prime * result + ((getoOrgCode() == null) ? 0 : getoOrgCode().hashCode());
        result = prime * result + ((getoOrgName() == null) ? 0 : getoOrgName().hashCode());
        result = prime * result + ((gettOrgId() == null) ? 0 : gettOrgId().hashCode());
        result = prime * result + ((gettOrgCode() == null) ? 0 : gettOrgCode().hashCode());
        result = prime * result + ((gettOrgName() == null) ? 0 : gettOrgName().hashCode());
        result = prime * result + ((getOrgName() == null) ? 0 : getOrgName().hashCode());
        result = prime * result + ((getOrgId() == null) ? 0 : getOrgId().hashCode());
        result = prime * result + ((getOrgCode() == null) ? 0 : getOrgCode().hashCode());
        result = prime * result + ((getDealerCode() == null) ? 0 : getDealerCode().hashCode());
        result = prime * result + ((getDealerName() == null) ? 0 : getDealerName().hashCode());
        result = prime * result + ((getLinkman() == null) ? 0 : getLinkman().hashCode());
        result = prime * result + ((getLinktel() == null) ? 0 : getLinktel().hashCode());
        result = prime * result + ((getEmail() == null) ? 0 : getEmail().hashCode());
        result = prime * result + ((getFax() == null) ? 0 : getFax().hashCode());
        result = prime * result + ((getHelpTel() == null) ? 0 : getHelpTel().hashCode());
        result = prime * result + ((getOrderTel() == null) ? 0 : getOrderTel().hashCode());
        result = prime * result + ((getAddress() == null) ? 0 : getAddress().hashCode());
        result = prime * result + ((getLongitude() == null) ? 0 : getLongitude().hashCode());
        result = prime * result + ((getLatitude() == null) ? 0 : getLatitude().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getOrderDiscount() == null) ? 0 : getOrderDiscount().hashCode());
        result = prime * result + ((getQrcodeUrl() == null) ? 0 : getQrcodeUrl().hashCode());
        result = prime * result + ((getAppId() == null) ? 0 : getAppId().hashCode());
        result = prime * result + ((getAppsecret() == null) ? 0 : getAppsecret().hashCode());
        result = prime * result + ((getToken() == null) ? 0 : getToken().hashCode());
        result = prime * result + ((getWechatId() == null) ? 0 : getWechatId().hashCode());
        result = prime * result + ((getCompanyInfo() == null) ? 0 : getCompanyInfo().hashCode());
        result = prime * result + ((getAccesstoken() == null) ? 0 : getAccesstoken().hashCode());
        result = prime * result + ((getTokenTime() == null) ? 0 : getTokenTime().hashCode());
        result = prime * result + ((getTicketTime() == null) ? 0 : getTicketTime().hashCode());
        result = prime * result + ((getJsapiTicket() == null) ? 0 : getJsapiTicket().hashCode());
        result = prime * result + ((getWechatMenuStatus() == null) ? 0 : getWechatMenuStatus().hashCode());
        result = prime * result + ((getWechatMenuTime() == null) ? 0 : getWechatMenuTime().hashCode());
        result = prime * result + ((getCreateBy() == null) ? 0 : getCreateBy().hashCode());
        result = prime * result + ((getCreateDate() == null) ? 0 : getCreateDate().hashCode());
        result = prime * result + ((getUpdateBy() == null) ? 0 : getUpdateBy().hashCode());
        result = prime * result + ((getUpdateDate() == null) ? 0 : getUpdateDate().hashCode());
        result = prime * result + ((getWorkBegin() == null) ? 0 : getWorkBegin().hashCode());
        result = prime * result + ((getWorkEnd() == null) ? 0 : getWorkEnd().hashCode());
        return result;
    }
}