package com.fh.entity.organization;

import java.io.Serializable;
import java.util.Date;

public class BaseOrg implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_org.ORG_ID
     *
     * @mbggenerated Sun Mar 12 18:57:46 CST 2017
     */
    private String orgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_org.ORG_CODE
     *
     * @mbggenerated Sun Mar 12 18:57:46 CST 2017
     */
    private String orgCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_org.ORG_NAME
     *
     * @mbggenerated Sun Mar 12 18:57:46 CST 2017
     */
    private String orgName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_org.ORG_LEVEL
     *
     * @mbggenerated Sun Mar 12 18:57:46 CST 2017
     */
    private Integer orgLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_org.PARENT_ORG_ID
     *
     * @mbggenerated Sun Mar 12 18:57:46 CST 2017
     */
    private String parentOrgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_org.FIRST_PINYIN
     *
     * @mbggenerated Sun Mar 12 18:57:46 CST 2017
     */
    private String firstPinyin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_org.CREATE_BY
     *
     * @mbggenerated Sun Mar 12 18:57:46 CST 2017
     */
    private String createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_org.CREATE_DATE
     *
     * @mbggenerated Sun Mar 12 18:57:46 CST 2017
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_org.UPDATE_BY
     *
     * @mbggenerated Sun Mar 12 18:57:46 CST 2017
     */
    private String updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_org.UPDATE_DATE
     *
     * @mbggenerated Sun Mar 12 18:57:46 CST 2017
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table base_org
     *
     * @mbggenerated Sun Mar 12 18:57:46 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_org.ORG_ID
     *
     * @return the value of base_org.ORG_ID
     *
     * @mbggenerated Sun Mar 12 18:57:46 CST 2017
     */
    public String getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_org.ORG_ID
     *
     * @param orgId the value for base_org.ORG_ID
     *
     * @mbggenerated Sun Mar 12 18:57:46 CST 2017
     */
    public void setOrgId(String orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_org.ORG_CODE
     *
     * @return the value of base_org.ORG_CODE
     *
     * @mbggenerated Sun Mar 12 18:57:46 CST 2017
     */
    public String getOrgCode() {
        return orgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_org.ORG_CODE
     *
     * @param orgCode the value for base_org.ORG_CODE
     *
     * @mbggenerated Sun Mar 12 18:57:46 CST 2017
     */
    public void setOrgCode(String orgCode) {
        this.orgCode = orgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_org.ORG_NAME
     *
     * @return the value of base_org.ORG_NAME
     *
     * @mbggenerated Sun Mar 12 18:57:46 CST 2017
     */
    public String getOrgName() {
        return orgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_org.ORG_NAME
     *
     * @param orgName the value for base_org.ORG_NAME
     *
     * @mbggenerated Sun Mar 12 18:57:46 CST 2017
     */
    public void setOrgName(String orgName) {
        this.orgName = orgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_org.ORG_LEVEL
     *
     * @return the value of base_org.ORG_LEVEL
     *
     * @mbggenerated Sun Mar 12 18:57:46 CST 2017
     */
    public Integer getOrgLevel() {
        return orgLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_org.ORG_LEVEL
     *
     * @param orgLevel the value for base_org.ORG_LEVEL
     *
     * @mbggenerated Sun Mar 12 18:57:46 CST 2017
     */
    public void setOrgLevel(Integer orgLevel) {
        this.orgLevel = orgLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_org.PARENT_ORG_ID
     *
     * @return the value of base_org.PARENT_ORG_ID
     *
     * @mbggenerated Sun Mar 12 18:57:46 CST 2017
     */
    public String getParentOrgId() {
        return parentOrgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_org.PARENT_ORG_ID
     *
     * @param parentOrgId the value for base_org.PARENT_ORG_ID
     *
     * @mbggenerated Sun Mar 12 18:57:46 CST 2017
     */
    public void setParentOrgId(String parentOrgId) {
        this.parentOrgId = parentOrgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_org.FIRST_PINYIN
     *
     * @return the value of base_org.FIRST_PINYIN
     *
     * @mbggenerated Sun Mar 12 18:57:46 CST 2017
     */
    public String getFirstPinyin() {
        return firstPinyin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_org.FIRST_PINYIN
     *
     * @param firstPinyin the value for base_org.FIRST_PINYIN
     *
     * @mbggenerated Sun Mar 12 18:57:46 CST 2017
     */
    public void setFirstPinyin(String firstPinyin) {
        this.firstPinyin = firstPinyin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_org.CREATE_BY
     *
     * @return the value of base_org.CREATE_BY
     *
     * @mbggenerated Sun Mar 12 18:57:46 CST 2017
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_org.CREATE_BY
     *
     * @param createBy the value for base_org.CREATE_BY
     *
     * @mbggenerated Sun Mar 12 18:57:46 CST 2017
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_org.CREATE_DATE
     *
     * @return the value of base_org.CREATE_DATE
     *
     * @mbggenerated Sun Mar 12 18:57:46 CST 2017
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_org.CREATE_DATE
     *
     * @param createDate the value for base_org.CREATE_DATE
     *
     * @mbggenerated Sun Mar 12 18:57:46 CST 2017
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_org.UPDATE_BY
     *
     * @return the value of base_org.UPDATE_BY
     *
     * @mbggenerated Sun Mar 12 18:57:46 CST 2017
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_org.UPDATE_BY
     *
     * @param updateBy the value for base_org.UPDATE_BY
     *
     * @mbggenerated Sun Mar 12 18:57:46 CST 2017
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_org.UPDATE_DATE
     *
     * @return the value of base_org.UPDATE_DATE
     *
     * @mbggenerated Sun Mar 12 18:57:46 CST 2017
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_org.UPDATE_DATE
     *
     * @param updateDate the value for base_org.UPDATE_DATE
     *
     * @mbggenerated Sun Mar 12 18:57:46 CST 2017
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_org
     *
     * @mbggenerated Sun Mar 12 18:57:46 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        BaseOrg other = (BaseOrg) that;
        return (this.getOrgId() == null ? other.getOrgId() == null : this.getOrgId().equals(other.getOrgId()))
            && (this.getOrgCode() == null ? other.getOrgCode() == null : this.getOrgCode().equals(other.getOrgCode()))
            && (this.getOrgName() == null ? other.getOrgName() == null : this.getOrgName().equals(other.getOrgName()))
            && (this.getOrgLevel() == null ? other.getOrgLevel() == null : this.getOrgLevel().equals(other.getOrgLevel()))
            && (this.getParentOrgId() == null ? other.getParentOrgId() == null : this.getParentOrgId().equals(other.getParentOrgId()))
            && (this.getFirstPinyin() == null ? other.getFirstPinyin() == null : this.getFirstPinyin().equals(other.getFirstPinyin()))
            && (this.getCreateBy() == null ? other.getCreateBy() == null : this.getCreateBy().equals(other.getCreateBy()))
            && (this.getCreateDate() == null ? other.getCreateDate() == null : this.getCreateDate().equals(other.getCreateDate()))
            && (this.getUpdateBy() == null ? other.getUpdateBy() == null : this.getUpdateBy().equals(other.getUpdateBy()))
            && (this.getUpdateDate() == null ? other.getUpdateDate() == null : this.getUpdateDate().equals(other.getUpdateDate()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_org
     *
     * @mbggenerated Sun Mar 12 18:57:46 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getOrgId() == null) ? 0 : getOrgId().hashCode());
        result = prime * result + ((getOrgCode() == null) ? 0 : getOrgCode().hashCode());
        result = prime * result + ((getOrgName() == null) ? 0 : getOrgName().hashCode());
        result = prime * result + ((getOrgLevel() == null) ? 0 : getOrgLevel().hashCode());
        result = prime * result + ((getParentOrgId() == null) ? 0 : getParentOrgId().hashCode());
        result = prime * result + ((getFirstPinyin() == null) ? 0 : getFirstPinyin().hashCode());
        result = prime * result + ((getCreateBy() == null) ? 0 : getCreateBy().hashCode());
        result = prime * result + ((getCreateDate() == null) ? 0 : getCreateDate().hashCode());
        result = prime * result + ((getUpdateBy() == null) ? 0 : getUpdateBy().hashCode());
        result = prime * result + ((getUpdateDate() == null) ? 0 : getUpdateDate().hashCode());
        return result;
    }
}