package com.fh.entity.file;

import java.io.Serializable;
import java.util.Date;

public class ComFile implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_file.FILE_ID
     *
     * @mbggenerated Tue Mar 14 20:02:31 CST 2017
     */
    private Long fileId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_file.BUS_POINT
     *
     * @mbggenerated Tue Mar 14 20:02:31 CST 2017
     */
    private Integer busPoint;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_file.BUS_ID
     *
     * @mbggenerated Tue Mar 14 20:02:31 CST 2017
     */
    private Long busId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_file.FILE_TYPE
     *
     * @mbggenerated Tue Mar 14 20:02:31 CST 2017
     */
    private Integer fileType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_file.FILE_URL
     *
     * @mbggenerated Tue Mar 14 20:02:31 CST 2017
     */
    private String fileUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_file.FILE_NAME
     *
     * @mbggenerated Tue Mar 14 20:02:31 CST 2017
     */
    private String fileName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_file.CREATE_BY
     *
     * @mbggenerated Tue Mar 14 20:02:31 CST 2017
     */
    private String createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_file.CREATE_DATE
     *
     * @mbggenerated Tue Mar 14 20:02:31 CST 2017
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_file.UPDATE_BY
     *
     * @mbggenerated Tue Mar 14 20:02:31 CST 2017
     */
    private String updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_file.UPDATE_DATE
     *
     * @mbggenerated Tue Mar 14 20:02:31 CST 2017
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table com_file
     *
     * @mbggenerated Tue Mar 14 20:02:31 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_file.FILE_ID
     *
     * @return the value of com_file.FILE_ID
     *
     * @mbggenerated Tue Mar 14 20:02:31 CST 2017
     */
    public Long getFileId() {
        return fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_file.FILE_ID
     *
     * @param fileId the value for com_file.FILE_ID
     *
     * @mbggenerated Tue Mar 14 20:02:31 CST 2017
     */
    public void setFileId(Long fileId) {
        this.fileId = fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_file.BUS_POINT
     *
     * @return the value of com_file.BUS_POINT
     *
     * @mbggenerated Tue Mar 14 20:02:31 CST 2017
     */
    public Integer getBusPoint() {
        return busPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_file.BUS_POINT
     *
     * @param busPoint the value for com_file.BUS_POINT
     *
     * @mbggenerated Tue Mar 14 20:02:31 CST 2017
     */
    public void setBusPoint(Integer busPoint) {
        this.busPoint = busPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_file.BUS_ID
     *
     * @return the value of com_file.BUS_ID
     *
     * @mbggenerated Tue Mar 14 20:02:31 CST 2017
     */
    public Long getBusId() {
        return busId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_file.BUS_ID
     *
     * @param busId the value for com_file.BUS_ID
     *
     * @mbggenerated Tue Mar 14 20:02:31 CST 2017
     */
    public void setBusId(Long busId) {
        this.busId = busId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_file.FILE_TYPE
     *
     * @return the value of com_file.FILE_TYPE
     *
     * @mbggenerated Tue Mar 14 20:02:31 CST 2017
     */
    public Integer getFileType() {
        return fileType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_file.FILE_TYPE
     *
     * @param fileType the value for com_file.FILE_TYPE
     *
     * @mbggenerated Tue Mar 14 20:02:31 CST 2017
     */
    public void setFileType(Integer fileType) {
        this.fileType = fileType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_file.FILE_URL
     *
     * @return the value of com_file.FILE_URL
     *
     * @mbggenerated Tue Mar 14 20:02:31 CST 2017
     */
    public String getFileUrl() {
        return fileUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_file.FILE_URL
     *
     * @param fileUrl the value for com_file.FILE_URL
     *
     * @mbggenerated Tue Mar 14 20:02:31 CST 2017
     */
    public void setFileUrl(String fileUrl) {
        this.fileUrl = fileUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_file.FILE_NAME
     *
     * @return the value of com_file.FILE_NAME
     *
     * @mbggenerated Tue Mar 14 20:02:31 CST 2017
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_file.FILE_NAME
     *
     * @param fileName the value for com_file.FILE_NAME
     *
     * @mbggenerated Tue Mar 14 20:02:31 CST 2017
     */
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_file.CREATE_BY
     *
     * @return the value of com_file.CREATE_BY
     *
     * @mbggenerated Tue Mar 14 20:02:31 CST 2017
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_file.CREATE_BY
     *
     * @param createBy the value for com_file.CREATE_BY
     *
     * @mbggenerated Tue Mar 14 20:02:31 CST 2017
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_file.CREATE_DATE
     *
     * @return the value of com_file.CREATE_DATE
     *
     * @mbggenerated Tue Mar 14 20:02:31 CST 2017
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_file.CREATE_DATE
     *
     * @param createDate the value for com_file.CREATE_DATE
     *
     * @mbggenerated Tue Mar 14 20:02:31 CST 2017
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_file.UPDATE_BY
     *
     * @return the value of com_file.UPDATE_BY
     *
     * @mbggenerated Tue Mar 14 20:02:31 CST 2017
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_file.UPDATE_BY
     *
     * @param updateBy the value for com_file.UPDATE_BY
     *
     * @mbggenerated Tue Mar 14 20:02:31 CST 2017
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_file.UPDATE_DATE
     *
     * @return the value of com_file.UPDATE_DATE
     *
     * @mbggenerated Tue Mar 14 20:02:31 CST 2017
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_file.UPDATE_DATE
     *
     * @param updateDate the value for com_file.UPDATE_DATE
     *
     * @mbggenerated Tue Mar 14 20:02:31 CST 2017
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table com_file
     *
     * @mbggenerated Tue Mar 14 20:02:31 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ComFile other = (ComFile) that;
        return (this.getFileId() == null ? other.getFileId() == null : this.getFileId().equals(other.getFileId()))
            && (this.getBusPoint() == null ? other.getBusPoint() == null : this.getBusPoint().equals(other.getBusPoint()))
            && (this.getBusId() == null ? other.getBusId() == null : this.getBusId().equals(other.getBusId()))
            && (this.getFileType() == null ? other.getFileType() == null : this.getFileType().equals(other.getFileType()))
            && (this.getFileUrl() == null ? other.getFileUrl() == null : this.getFileUrl().equals(other.getFileUrl()))
            && (this.getFileName() == null ? other.getFileName() == null : this.getFileName().equals(other.getFileName()))
            && (this.getCreateBy() == null ? other.getCreateBy() == null : this.getCreateBy().equals(other.getCreateBy()))
            && (this.getCreateDate() == null ? other.getCreateDate() == null : this.getCreateDate().equals(other.getCreateDate()))
            && (this.getUpdateBy() == null ? other.getUpdateBy() == null : this.getUpdateBy().equals(other.getUpdateBy()))
            && (this.getUpdateDate() == null ? other.getUpdateDate() == null : this.getUpdateDate().equals(other.getUpdateDate()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table com_file
     *
     * @mbggenerated Tue Mar 14 20:02:31 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getFileId() == null) ? 0 : getFileId().hashCode());
        result = prime * result + ((getBusPoint() == null) ? 0 : getBusPoint().hashCode());
        result = prime * result + ((getBusId() == null) ? 0 : getBusId().hashCode());
        result = prime * result + ((getFileType() == null) ? 0 : getFileType().hashCode());
        result = prime * result + ((getFileUrl() == null) ? 0 : getFileUrl().hashCode());
        result = prime * result + ((getFileName() == null) ? 0 : getFileName().hashCode());
        result = prime * result + ((getCreateBy() == null) ? 0 : getCreateBy().hashCode());
        result = prime * result + ((getCreateDate() == null) ? 0 : getCreateDate().hashCode());
        result = prime * result + ((getUpdateBy() == null) ? 0 : getUpdateBy().hashCode());
        result = prime * result + ((getUpdateDate() == null) ? 0 : getUpdateDate().hashCode());
        return result;
    }
}